//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITI.Data.DBmodel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Branch
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Branch()
        {
            this.PlatfromIntakes = new HashSet<PlatfromIntake>();
        }
    
        public int BranchID { get; set; }
        public string BranchName { get; set; }
        public string arabicname { get; set; }
        public System.Guid msrepl_tran_version { get; set; }
        public Nullable<int> trainbranchid { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlatfromIntake> PlatfromIntakes { get; set; }
        public virtual TrainBranch TrainBranch { get; set; }
    }
}
