//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITI.Data.DBmodel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Complaint_Stage
    {
        public int Stage_ID { get; set; }
        public int Comolaint_Id { get; set; }
        public System.DateTime EnterDate { get; set; }
        public Nullable<System.DateTime> ExitDate { get; set; }
        public int FK_EmployeeID { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Stage Stage { get; set; }
        public virtual Student_Complaints Student_Complaints { get; set; }
    }
}
