//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITI.Data.DBmodel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.UserDevices = new HashSet<UserDevice>();
            this.TrackManagers = new HashSet<TrackManager>();
            this.TrackSupervisors = new HashSet<TrackSupervisor>();
        }
    
        public int EmployeeID { get; set; }
        public string InstructorName { get; set; }
        public int BranchID { get; set; }
        public string IPassword { get; set; }
        public string UserName2 { get; set; }
        public Nullable<int> PlatformID { get; set; }
        public Nullable<int> RoleID { get; set; }
        public Nullable<int> TypeID { get; set; }
        public string ArabicName { get; set; }
        public Nullable<int> CertificateID { get; set; }
        public string FirstNameEn { get; set; }
        public string SecondNameEn { get; set; }
        public string barcode { get; set; }
        public string imagepath { get; set; }
        public Nullable<int> org_branchid { get; set; }
        public Nullable<int> StatusID { get; set; }
        public Nullable<int> PositionID { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public Nullable<System.DateTime> HiringDate { get; set; }
        public string ThirdNameEn { get; set; }
        public string FourthNameEn { get; set; }
        public string FirstNameAr { get; set; }
        public string SecondNameAr { get; set; }
        public string ThirdNameAr { get; set; }
        public string FourthNameAr { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string PhoneNo { get; set; }
        public string MobileNo { get; set; }
        public string ExtenistonNo { get; set; }
        public string Gender { get; set; }
        public string Address { get; set; }
        public string Mail { get; set; }
        public Nullable<int> MaritalStatus { get; set; }
        public Nullable<int> MilitaryStatus { get; set; }
        public Nullable<int> UniversityID { get; set; }
        public Nullable<int> FacultyID { get; set; }
        public Nullable<int> IntakeID { get; set; }
        public Nullable<int> Flag { get; set; }
        public Nullable<int> GraduationYear { get; set; }
        public string Grade { get; set; }
        public Nullable<int> AttendanceFlag { get; set; }
        public string PositionName { get; set; }
        public Nullable<int> EmpStatus { get; set; }
        public System.Guid msrepl_tran_version { get; set; }
        public string IDCard { get; set; }
        public string AttachmentID { get; set; }
        public string AttachmentCV { get; set; }
        public Nullable<int> ATMStatus { get; set; }
        public string ATMNo { get; set; }
        public Nullable<int> SpecialRate { get; set; }
        public string RateNotes { get; set; }
        public Nullable<System.DateTime> ATMExpiryDate { get; set; }
        public Nullable<int> Religionid { get; set; }
        public Nullable<int> empno { get; set; }
        public Nullable<int> cat { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserDevice> UserDevices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TrackManager> TrackManagers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TrackSupervisor> TrackSupervisors { get; set; }
    }
}
