//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITI.Data.DBmodel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ITIEntities : DbContext
    {
        public ITIEntities()
            : base("name=ITIEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<StudentBasicData> StudentBasicDatas { get; set; }
        public virtual DbSet<UserDevice> UserDevices { get; set; }
        public virtual DbSet<Course> Courses { get; set; }
        public virtual DbSet<CourseManual> CourseManuals { get; set; }
        public virtual DbSet<PlatfromIntake> PlatfromIntakes { get; set; }
        public virtual DbSet<subTrack> subTracks { get; set; }
        public virtual DbSet<TrackManual> TrackManuals { get; set; }
        public virtual DbSet<Branch> Branches { get; set; }
        public virtual DbSet<Intake> Intakes { get; set; }
        public virtual DbSet<program> programs { get; set; }
        public virtual DbSet<ProgramIntake> ProgramIntakes { get; set; }
        public virtual DbSet<TrackManager> TrackManagers { get; set; }
        public virtual DbSet<TrackSupervisor> TrackSupervisors { get; set; }
        public virtual DbSet<TrainBranch> TrainBranches { get; set; }
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<Complain_Category> Complain_Category { get; set; }
        public virtual DbSet<Student_Complaints> Student_Complaints { get; set; }
        public virtual DbSet<Complaint_Stage> Complaint_Stage { get; set; }
        public virtual DbSet<Stage> Stages { get; set; }
    }
}
