//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITI.Data.DBmodel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlatfromIntake
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PlatfromIntake()
        {
            this.StudentBasicDatas = new HashSet<StudentBasicData>();
            this.TrackManuals = new HashSet<TrackManual>();
            this.TrackManagers = new HashSet<TrackManager>();
            this.TrackSupervisors = new HashSet<TrackSupervisor>();
        }
    
        public int PlatformIntakeID { get; set; }
        public Nullable<int> BranchID { get; set; }
        public Nullable<int> SubTrackID { get; set; }
        public Nullable<int> ProgramIntakeID { get; set; }
        public Nullable<int> OwnedBy { get; set; }
        public string GraduateProfile { get; set; }
    
        public virtual subTrack subTrack { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentBasicData> StudentBasicDatas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TrackManual> TrackManuals { get; set; }
        public virtual Branch Branch { get; set; }
        public virtual ProgramIntake ProgramIntake { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TrackManager> TrackManagers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TrackSupervisor> TrackSupervisors { get; set; }
    }
}
