//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITI.Data.DBmodel
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentsProfessional
    {
        public int ID { get; set; }
        public int StudentID { get; set; }
        public string ProfessionalNetworkName { get; set; }
        public string ProfessionalNetworkURL { get; set; }
    
        public virtual StudentBasicData StudentBasicData { get; set; }
    }
}
