//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITI.Data.DBmodel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student_Complaints
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Student_Complaints()
        {
            this.Complaint_Stage = new HashSet<Complaint_Stage>();
        }
    
        public int ID { get; set; }
        public string Body { get; set; }
        public Nullable<bool> IsSolved { get; set; }
        public int FK_Student_Id { get; set; }
        public int FK_Category_Id { get; set; }
        public int CurrentStage { get; set; }
        public string Subject { get; set; }
        public string Solution { get; set; }
        public string Status { get; set; }
        public bool Type { get; set; }
    
        public virtual Complain_Category Complain_Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Complaint_Stage> Complaint_Stage { get; set; }
        public virtual StudentBasicData StudentBasicData1 { get; set; }
    }
}
